### ISSUE TITLE
Es lässt sich nichts hinzufügen ...

### ISSUE THREAD

**Issue by BNils** [diddipoeler/joomleague-2-komplettpaket#63]
Hallo,

ich habe Joomla 2.5.28 + joomleague-2-komplettpaket. Ich habe das Problem, das ich nichts hinzufügen kann. Kein Sportart, keine Saison nichts. Ich erstelle z.B. eine neue Sportart (fussball) und wenn ich dann auch speichern & schließen drücke, passiert einfach nichts. Das habe ich überall.

Wenn ich einen Verein hinzufügen möchte. Steht oben folgende Fehlermeldung:

`Notice: Undefined property: stdClass::$merge_teams in .../administrator/components/com_joomleague/views/club/view.html.php on line 43`

Das gleiche hatte ich mit Joomla 3.5 und dem sportsmanagement. Genau das gleiche.

Wo dran könnte das liegen?

**Comment by diddipoeler** [comment]
für jl2 komplettpaket im backend die komponente aufrufen, dann optionen und einmal
speichern. für die neue jsm komponente bitte alle fragen hier reinstellen: https://github.com/diddipoeler/sportsmanagement/issues ansonsten auf http://www.fussballineuropa.de/

**Comment by BNils** [comment]
okay, wußte ich nicht.

danke für die Hilfe, klappt super.
